id: A4595F292
base_file: f3393.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:06:43.884213
  last_modified_at: 2022-06-17 14:06:43.884267
