id: A4595F292
base_file: f341D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:06:43.962258
  last_modified_at: 2022-06-17 14:06:43.962273
